server:
  port: 2023

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/SelfWeb?useUnicode=true&characterEncoding=utf-8
    username: your_username
    password: your_password
    driver-class-name: com.mysql.jdbc.Driver